export const robotNames: string[] = [
  "CyberZoid",
  "MechaX",
  "Boltimus",
  "GizmoTron",
  "NeonDroid",
  "RoboSpecter",
  "ZapBot",
  "TitaniumX",
  "ElectroGear",
  "QuantumBot",
  "HyperMech",
  "TurboZoid",
  "OmegaBot",
  "GlitchMaster",
  "CyberNova",
  "PlasmaDroid",
  "ByteCruncher",
  "ZetaMech",
  "NanoCore",
  "FusionBot",
];

export const avatarBotNames: string[] = [
  "Eden",
  "Alexander",
  "Ryker",
  "Aidan",
  "Nolan",
  "Jessica",
  "Andrea",
  "Sarah",
  "Robert",
  "Ryan",
  "George",
  "Kimberly",
  "Destiny",
  "Oliver",
  "Adrian",
  "Kingston",
  "Sawyer",
  "Mackenzie",
  "Sadie",
];

export const tailwindColors = [
    "bg-sky-600",
    "bg-blue-600",
    "bg-cyan-600",
    "bg-indigo-600",
    "bg-purple-600",
    "bg-amber-600",
    "bg-orange-600",
    "bg-red-600",
    "bg-green-600",
    "bg-emerald-600",
]